/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projekjavafix.gui;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import projekjavafix.controller.GameController;
import projekjavafix.controller.GameController.GuessResult;
import projekjavafix.controller.GameController.Player;

/**
 *
 * @author Adinata
 */
public class GamePanel extends javax.swing.JPanel {
    
    private final MainFrame.NavigationListener listener;
    private GameController gameController;
    
    public GamePanel(MainFrame.NavigationListener listener) {
        this.listener = listener;
        initComponents();
        initializeGame();
        setupEventListeners();
    }
    
    private void initializeGame() {
        resetGame();
        updateGameDisplay();
    }
    
    private void resetGame() {
        this.gameController = new GameController();
        playerList.clearSelection();
    }
    
    private void setupEventListeners() {
        tebakButton.addActionListener(e -> handleGuess());
        backButton.addActionListener(e -> listener.showStartPanel());
    }
    
    private void updateGameDisplay() {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (Player player : gameController.getPlayers()) { // Now works with the import
            model.addElement(player.getName() + " - " + player.getRole());
        }
        playerList.setModel(model);
        
        clueLabel.setText("Petunjuk: " + gameController.getNextClue());
        scoreLabel.setText("Skor: " + gameController.getScore());
        livesLabel.setText("Nyawa: " + "❤".repeat(gameController.getLives()));
        roundLabel.setText("Ronde: " + gameController.getRound());
    }
    
    private void handleGuess() {
        String selected = playerList.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Pilih pemain terlebih dahulu!");
            return;
        }
        
        String playerName = selected.split(" - ")[0].trim();
        GuessResult result = gameController.processGuess(playerName);
        
        JOptionPane.showMessageDialog(this, result.message);
        
        if (result.isGameOver) {
            int option = JOptionPane.showConfirmDialog(
                this, 
                "Game Over! Skor akhir: " + gameController.getScore() + "\nMain lagi?",
                "Game Over",
                JOptionPane.YES_NO_OPTION
            );
            
            if (option == JOptionPane.YES_OPTION) {
                resetGame();
            } else {
                listener.showStartPanel();
                return;
            }
        }
        
        updateGameDisplay();
    }


    
    public void setPlayerList(java.util.List<String> players) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String player : players) {
            model.addElement(player);
        }
        playerList.setModel(model);
    }

    public void setClue(String clue) {
        clueLabel.setText("Clue: " + clue);
    }

    public void setScore(int score) {
        scoreLabel.setText("Score: " + score);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        titleLabel1 = new javax.swing.JLabel();
        infoLabel1 = new javax.swing.JLabel();
        clueLabel1 = new javax.swing.JLabel();
        scoreLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        tebakButton1 = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        statusLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        playerList1 = new javax.swing.JList<>();
        titleLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        PanelTombolGab = new javax.swing.JPanel();
        tebakButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerList = new javax.swing.JList<>();
        panelClueScore = new javax.swing.JPanel();
        clueLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        livesLabel = new javax.swing.JLabel();
        roundLabel = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(255, 245, 228));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        titleLabel1.setText("Tebak Impostor - Round 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(1, 228, 0, 0);
        jPanel3.add(titleLabel1, gridBagConstraints);

        infoLabel1.setText("Pemain: 5 | Impostor: 1 | ❤️❤️❤️");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 213, 0, 0);
        jPanel3.add(infoLabel1, gridBagConstraints);

        clueLabel1.setText("Clue: Tempat Umum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 126, 0, 0);
        jPanel3.add(clueLabel1, gridBagConstraints);

        scoreLabel1.setText("Score: 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 71, 0, 0);
        jPanel3.add(scoreLabel1, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(255, 245, 228));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        tebakButton1.setText("Tebak");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 6;
        jPanel4.add(tebakButton1, gridBagConstraints);

        backButton1.setText("Kembali");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel4.add(backButton1, gridBagConstraints);

        statusLabel1.setText("Status: Silahkan Pilih Pemain");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        jPanel4.add(statusLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 199, 17, 0);
        jPanel3.add(jPanel4, gridBagConstraints);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 652);
        jPanel3.add(jPanel5, gridBagConstraints);

        playerList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Player 1", "Player 2", "Player 3", "Player 4", "Player 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        playerList1.setPreferredSize(new java.awt.Dimension(250, 159));
        jScrollPane2.setViewportView(playerList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 246;
        gridBagConstraints.ipady = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(17, 154, 0, 0);
        jPanel3.add(jScrollPane2, gridBagConstraints);

        setBackground(new java.awt.Color(255, 245, 228));
        setMaximumSize(new java.awt.Dimension(400, 150));
        setPreferredSize(new java.awt.Dimension(700, 581));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        titleLabel.setText("Tebak Impostor");

        infoLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        infoLabel.setText("Pemain: 5 | Impostor: 1");

        PanelTombolGab.setBackground(new java.awt.Color(255, 245, 228));
        PanelTombolGab.setLayout(new java.awt.GridBagLayout());

        tebakButton.setText("Tebak");
        PanelTombolGab.add(tebakButton, new java.awt.GridBagConstraints());

        backButton.setText("Kembali");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        PanelTombolGab.add(backButton, gridBagConstraints);

        statusLabel.setText("Status: Silahkan Pilih Pemain");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 12);
        PanelTombolGab.add(statusLabel, gridBagConstraints);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        playerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Player 1", "Player 2", "Player 3", "Player 4", "Player 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        playerList.setPreferredSize(new java.awt.Dimension(250, 159));
        jScrollPane1.setViewportView(playerList);

        panelClueScore.setLayout(new java.awt.GridBagLayout());

        clueLabel.setText("Clue: Tempat Umum");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 2, 10);
        panelClueScore.add(clueLabel, gridBagConstraints);

        scoreLabel.setText("Score: 0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 15, 3, 15);
        panelClueScore.add(scoreLabel, gridBagConstraints);

        livesLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        livesLabel.setText("❤❤❤");

        roundLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        roundLabel.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(514, 514, 514)
                        .addComponent(PanelTombolGab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(414, 414, 414)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(titleLabel)
                        .addGap(18, 18, 18)
                        .addComponent(roundLabel))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(panelClueScore, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(442, 442, 442)
                            .addComponent(infoLabel)
                            .addGap(18, 18, 18)
                            .addComponent(livesLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(roundLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoLabel)
                    .addComponent(livesLabel))
                .addGap(60, 60, 60)
                .addComponent(panelClueScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(PanelTombolGab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if (listener != null) {
        listener.showStartPanel();
    }
    }//GEN-LAST:event_backButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelTombolGab;
    private javax.swing.JButton backButton;
    private javax.swing.JButton backButton1;
    private javax.swing.JLabel clueLabel;
    private javax.swing.JLabel clueLabel1;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel livesLabel;
    private javax.swing.JPanel panelClueScore;
    private javax.swing.JList<String> playerList;
    private javax.swing.JList<String> playerList1;
    private javax.swing.JLabel roundLabel;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreLabel1;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel statusLabel1;
    private javax.swing.JButton tebakButton;
    private javax.swing.JButton tebakButton1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    // End of variables declaration//GEN-END:variables
}
