/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projekjavafix.gui;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Adinata
 */
public class GamePanel extends javax.swing.JPanel {
    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        initComponents();

        titleLabel.setText("Tebak Impostor");
        clueLabel.setText("Clue: ???");
        scoreLabel.setText("Score: 0");
        playerList.setModel(new javax.swing.DefaultListModel<>());

        tebakButton.addActionListener(e -> {
            String selected = playerList.getSelectedValue();
            if (selected != null) {
                System.out.println("Kamu memilih: " + selected);
            } else {
                JOptionPane.showMessageDialog(this, "Pilih dulu salah satu pemain!");
            }
        });
    }
    
    public void setPlayerList(java.util.List<String> players) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String player : players) {
            model.addElement(player);
        }
        playerList.setModel(model);
    }

    public void setClue(String clue) {
        clueLabel.setText("Clue: " + clue);
    }

    public void setScore(int score) {
        scoreLabel.setText("Score: " + score);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        clueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        playerList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tebakButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        statusLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 245, 228));

        titleLabel.setText("Tebak Impostor - Round 1");

        infoLabel.setText("Pemain: 5 | Impostor: 1 | ❤️❤️❤️");

        clueLabel.setText("Clue: Tempat Umum");

        playerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Player 1", "Player 2", "Player 3", "Player 4", "Player 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(playerList);

        tebakButton.setText("Tebak");

        backButton.setText("Kembali");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        statusLabel.setText("Status: Silahkan Pilih Pemain");

        scoreLabel.setText("Score: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(infoLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(clueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(titleLabel)
                                .addGap(18, 18, 18)
                                .addComponent(scoreLabel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(107, 107, 107))
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tebakButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(titleLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(scoreLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clueLabel)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(tebakButton))
                .addGap(18, 18, 18)
                .addComponent(statusLabel)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel clueLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> playerList;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton tebakButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
